name: Build project check

on:
    pull_request:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ACTIONS_RUNNER_DEBUG: true
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16"

            - name: ls
              run: ls -la

            - name: Checkout war3js_unsafe repository
              uses: actions/checkout@v4
              with:
                  repository: kirill-782/war3js_unsafe
                  path: unsafe

            - name: ls
              run: ls -la

            - name: Checkout current repository
              uses: actions/checkout@v4
              with:
                  path: bootstrap

            - name: ls
              run: ls -la

            - name: Switch to bootstrap project directory
              run: cd bootstrap

            - name: ls
              run: ls -la

            - name: Install dependencies
              run: npm install

            - name: Bundle js file
              run: npm run bundle

            - name: Bundle types
              run: npm run typesgen
