name: Build project check

on:
    pull_request:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16"

            - name: Checkout war3js_unsafe repository
              uses: actions/checkout@v4
              with:
                  repository: kirill-782/war3js_unsafe
                  path: unsafe

            - name: Install unsafe dependencies
              run: npm install
              working-directory: ./unsafe

            - name: Build unsafe
              run: npm run build
              working-directory: ./unsafe

            - name: Checkout current repository
              uses: actions/checkout@v4
              with:
                  path: bootstrap

            - name: Install dependencies
              run: npm install
              working-directory: ./bootstrap

            - name: Bundle js file
              run: npm run bundle
              working-directory: ./bootstrap

            - name: Bundle types
              run: npm run typesgen
              working-directory: ./bootstrap
